spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: app_user
    password: app_user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
