spring.profiles.active=postgres

spring.application.name=user-service

spring.flyway.locations=classpath:db/migration/{vendor}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.app.jwtSecret=mySecret0978354097650835lkajflkncao0kmnc091234
spring.app.jwtExpirationsMs=172800000