-- H2: roles table (use VARCHAR + CHECK to mimic enum)
CREATE TABLE IF NOT EXISTS roles (
    role_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL UNIQUE,
    CONSTRAINT roles_role_name_ck CHECK (role_name IN ('ROLE_USER', 'ROLE_ADMIN'))
);
