-- H2: users table (no CITEXT, no timestamptz)
CREATE TABLE IF NOT EXISTS users (
    user_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                   VARCHAR(20)  NOT NULL,
    email                      VARCHAR(50)  NOT NULL,
    password                   VARCHAR(120),

    account_non_locked         BOOLEAN DEFAULT TRUE NOT NULL,
    account_non_expired        BOOLEAN DEFAULT TRUE NOT NULL,
    credentials_non_expired    BOOLEAN DEFAULT TRUE NOT NULL,
    enabled                    BOOLEAN DEFAULT TRUE NOT NULL,

    credentials_expiry_date    DATE,
    account_expiry_date        DATE,

    two_factor_secret          VARCHAR(255),
    is_two_factor_auth_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    sign_up_method             VARCHAR(50),

    role_id                    INTEGER,
    created_date               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_date               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT fk_users_role     FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users(role_id);
