CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(20)  NOT NULL,
    email       VARCHAR(50)  NOT NULL,
    password VARCHAR(120),

    account_non_locked       BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_expired      BOOLEAN NOT NULL DEFAULT TRUE,
    credentials_non_expired  BOOLEAN NOT NULL DEFAULT TRUE,
    enabled                  BOOLEAN NOT NULL DEFAULT TRUE,

    credentials_expiry_date  DATE,
    account_expiry_date      DATE,

    two_factor_secret          VARCHAR(255),
    is_two_factor_auth_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    sign_up_method             VARCHAR(50),

    role_id INTEGER REFERENCES roles(role_id),

    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users(role_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_date := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
